name: Mirror to Rakbook

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:Rakbook/rakbook-projects.git"
          destination-repo: "git@rakbook.pl:rakbook-projects.git"
